### PR TITLE
digital_object.determine_druid note added re: get_druid_from: suri option

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made?

Out of an abundance of caution for PR sul-dlss/shared_configs/pull/1386

## How was this change tested?

test suite

## Which documentation and/or configurations were updated?

See sul-dlss/shared_configs/pull/1386.

NOTE:  please merge sul-dlss/shared_configs/pull/1386 after merging this.

### CODE REVIEW

**Comment by ndushay** [comment]
@mjgiarlo I elected NOT to remove remaining suri instances for 2 reasons:
- we're trying to move needed functionality from this repo to preassembly and deprecate the repo, as I understand it.
- the other occurrences are in example yml files -- I'm not sure what would be correct to put in its place, and i'm not sure if those examples are demonstrating desired functionality.

**Comment by ndushay** [comment]
```
$ ack suri
config/projects/TEMPLATE.yaml
83:  get_druid_from: 'suri'               # Only used with should_register = true.

config/projects/manifest_noreg_example.yaml
7:  get_druid_from:     'suri'

spec/test_data/project_config_files/local_dev_revs_with_tag.yaml
6:  get_druid_from:     'suri'

spec/test_data/project_config_files/local_dev_revs_no_contentMetadata.yaml
6:  get_druid_from:     'suri'

spec/test_data/project_config_files/local_dev_revs_bad_manifest.yaml
6:  get_druid_from:     'suri'

spec/test_data/project_config_files/local_dev_revs.yaml
6:  get_druid_from:     'suri'

README.md
624:pre-assemble other than ensuring your DRUIDs and/or barcodes match the ones in
630:template XML MODS file, placing with your YAML configuration file and ensuring

lib/pre_assembly/digital_object.rb
157:      # NOTE:  PR https://github.com/sul-dlss/lyberservices-scripts/pull/42 removed the option to get it from suri;

lib/pre_assembly/bundle.rb
152:          :get_druid_from=>[:suri,:container,:manifest,:druid_minter],
235:        validation_errors << "get_druid_from: 'suri' is only valid if should_register = true." if @project_style[:get_druid_from]==:suri # can't use SURI to get druid
```

**Comment by peetucket** [comment]
I think its fine to leave the other suri references noted - they are just in template files as Naomi noted, plus the repo is on its way out.

**Comment by mjgiarlo** [comment]
@ndushay @peetucket it's the two references in `lib/pre_assembly/bundle.rb` that I thought could be excised since they are dead code

**Comment by peetucket** [comment]
that's fine - could also rename that option to make it more clear ... its not really getting anything from suri directly despite the name of that setting, the druid will come from the registration service ... but given the fact that i don't think lyberservices-scripts is being used to accession content and register at the same time, not sure its worth the effort (maybe at least noted in the code?)

**Comment by mjgiarlo** [comment]
@ndushay @peetucket in a nutshell, why can't/shouldn't we do this: https://github.com/sul-dlss/lyberservices-scripts/pull/85 ?

**Comment by ndushay** [comment]
I now completely regret:
1.  taking on this suri-rails stuff
2.  making a benign change to a repo that would have been fine without the change.
3.  cleaning up after Justin Coyne.

**Comment by ndushay** [comment]
I mean, seriously, Mike:  I ADDED A HELPFUL COMMENT.   Justin didn't get pushback for his PR which actually may have broken stuff.  Can we just let it go?

**Comment by ndushay** [comment]
I truly don't like it when my simple PRs are piled on as an excuse to clean up the mess from earlier PRs -- if you want to fix that up - make a separate PR yourself.

**Comment by ndushay** [comment]
as for #85 -- the test didn't pass.   🤣

**Comment by mjgiarlo** [comment]
> as for #85 -- the test didn't pass.

they failed miserably, in fact!

**Comment by mjgiarlo** [comment]
@ndushay it's no biggie. I thought it was worth a quick test to see what would happen if those lines were removed. Turns out it not as simple as I'd hoped. I meant my initial review as a comment (a question, in fact!), not a change request. So, approving!

**Pull request merged**
